version: '3.1'

services:
  mysql:
    build: mysql/.
    ports:
#     - machine:container
      - "3307:3306"
#   untuk command khusus pada container
    command: --default-authentication-plugin=mysql_native_password
#   network antar container
    networks:
      my_network:
  hivemq:
    build: hivemq/.
    ports:
      - "1883:1883"
    networks:
      my_network:
volumes:
  db_data:
    external: true
networks:
  my_network:
    driver: bridge